# Generated by Django 4.1.3 on 2022-12-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsaleitems',
            name='categories',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
    ]
