# Generated by Django 4.1.3 on 2022-12-06 22:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_onsaleitems_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsaleitems',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.upload_to),
        ),
    ]
